version: "3"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - "../dev.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-udev", "-pdev"]
      interval: 30s
      timeout: 30s
      retries: 10

  redis:
    image: redis:7.0.4-alpine3.16

  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - "./nginx-app.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl/ssl.pem:/ssl/ssl.pem"
      - "./ssl/ssl.key:/ssl/ssl.key"

    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  app:
    image: letsync-service
    build:
      context: ../
      dockerfile: ./docker-compose/dockerfile-app
    volumes:
      - "../env/.env.prod:/etc/config/.env.prod"
    depends_on:
      db:
        condition: service_healthy